language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip

install:
  - go get github.com/smartystreets/goconvey/convey
  - go get github.com/davecgh/go-spew/spew

script: go test -v

